### PR TITLE
fix: parse_module cannot parse routes with more than one params

### LINKED ISSUE #52: `parse_module` Cannot Parse Routes With More than One Params
I recently discovered that routes containing more than one parameter are not parsed correctly by the current implementation.

### Example
Consider the following route template:
```plaintext
/path/[first]/to/[second]/api
```
The current parsing result is:
```plaintext
/path/{first]/to/[second}/api
```
However, the expected result should be:
```plaintext
/path/{first}/to/{second}/api
```

### Impact
This issue leads to incorrect parsing of parameters, causing the values of {first} and {second} to include extra characters, resulting in "{first]" and "[second}" instead of the expected values.

I am planning to submit a pull request to address this problem by fixing the parsing logic.

### PR DESCRIPTION
**Pull request by Andndre**
fixes #52

### CODE REVIEW

**Review by JacobLinCool — APPROVED** [review]
LGTM.

**Comment by JacobLinCool** [comment]
Please includes a changeset (run `pnpm changeset`) so that I can give credit to you in the release note.

**Comment by Andndre** [comment]
Alright, thx!

**Comment by Andndre** [comment]
Oops sorry I didn't saw that 😅

**Review by JacobLinCool — APPROVED** [review]

**Pull request merged**
